# frozen_string_literal: true

require "spec_helper"
require "tmpdir"

# Fidelity + degradation specs for the in-repo document converter
# (Rubino::Documents, #6). Fidelity is asserted by STRUCTURE and SIMILARITY,
# never byte-equality: Ruby's output legitimately differs from markitdown's and
# from one authoring tool to another, so we check that headings/lists/tables/
# links survive and that the body text overlaps the source -- not that bytes
# match. The binary fixtures (xlsx/docx/pdf) are generated by DocumentFixtures.
RSpec.describe Rubino::Documents do
  let(:fixtures) { File.expand_path("../../fixtures/documents", __dir__) }

  # Normalised token overlap (Jaccard) -- a cheap, whitespace-insensitive
  # similarity floor for "the words are mostly there", per the plan's fuzzy
  # similarity check rather than exact match.
  def similarity(actual, expected)
    a = expected.downcase.scan(/[a-z0-9]+/).to_set
    b = actual.downcase.scan(/[a-z0-9]+/).to_set
    return 1.0 if a.empty? && b.empty?

    (a & b).size.to_f / (a | b).size
  end

  describe ".to_markdown — pure-ruby formats (always available)" do
    it "csv -> a GFM table with header + separator row" do
      md = described_class.to_markdown(File.join(fixtures, "sample.csv"), mime: "text/csv")
      expect(md).to include("| Name | Role | Age |")
      expect(md).to match(/^\|---\|/)
      expect(md).to include("| Alice | Engineer | 30 |")
    end

    it "json -> pretty-printed inside a ```json fence" do
      md = described_class.to_markdown(File.join(fixtures, "sample.json"), mime: "application/json")
      expect(md).to start_with("```json")
      expect(md).to include('"name": "AziendaOS"')
      expect(md.strip).to end_with("```")
    end

    it "xml -> pretty-printed inside a ```xml fence" do
      md = described_class.to_markdown(File.join(fixtures, "sample.xml"), mime: "application/xml")
      expect(md).to start_with("```xml")
      expect(md).to include("<title>Ruby</title>")
    end

    it "html -> headings, a list, an inline link, and a GFM table" do
      md = described_class.to_markdown(File.join(fixtures, "sample.html"), mime: "text/html")
      expect(md).to include("# Report")
      expect(md).to include("## Items")
      expect(md).to include("[link](https://example.com)") # inline, not reference-style
      expect(md).to match(/^[*-] First$/)
      expect(md).to include("| Col A | Col B |")
      expect(md).to match(/^\|-+/) # a table separator row (kramdown's GFM form)
      expect(md).to include("| 1 | 2 |")
    end

    it "plain code -> fenced with a language hint inferred from the extension" do
      md = described_class.to_markdown(File.join(fixtures, "sample.rb"), mime: "text/x-ruby")
      expect(md).to start_with("```ruby")
      expect(md).to include('puts "hello"')
    end

    it "markdown passes through unchanged (not fenced)" do
      Dir.mktmpdir do |d|
        path = File.join(d, "note.md")
        File.write(path, "# Title\n\n- a\n- b\n")
        md = described_class.to_markdown(path, mime: "text/markdown")
        expect(md.strip).to eq("# Title\n\n- a\n- b")
      end
    end

    it "plain text with no known extension passes through verbatim" do
      md = described_class.to_markdown(File.join(fixtures, "sample.txt"), mime: "text/plain")
      expect(md).to include("Just plain text.")
      expect(md).not_to include("```")
    end
  end

  describe ".to_markdown — gem-backed formats (when the optional gem is present)" do
    it "xlsx -> a per-sheet heading + GFM table (roo)", if: roo_available? do
      md = described_class.to_markdown(File.join(fixtures, "sample.xlsx"))
      expect(md).to include("## Data")
      expect(md).to include("| Quarter | Revenue |")
      expect(md).to include("| Q1 | 100 |")
    end

    it "docx -> heading levels, list items, and bold run emphasis (docx gem)", if: docx_available? do
      md = described_class.to_markdown(File.join(fixtures, "sample.docx"))
      expect(md).to include("# Project Plan")  # Heading 1
      expect(md).to include("## Goals")        # Heading 2
      expect(md).to include("**important**")   # bold run
      expect(md).to match(/^- First goal$/)    # list paragraph
      expect(similarity(md, "Project Plan important Goals First goal Second goal")).to be > 0.5
    end

    it "pdf -> extracted text, pages joined (pdf-reader)", if: pdf_available? do
      md = described_class.to_markdown(File.join(fixtures, "sample.pdf"))
      expect(md).to include("Quarterly Report")
      expect(md).to include("Revenue grew this quarter.")
    end

    # KNOWN DIFFERENCE: a scanned / image-only PDF has no extractable text and
    # we perform no OCR -- we must return a clear note, never crash.
    it "scanned/image-only pdf -> a clear no-extractable-text note, not a crash", if: pdf_available? do
      md = described_class.to_markdown(File.join(fixtures, "scanned.pdf"))
      expect(md).to match(/no extractable text/i)
      expect(md).to match(/scanned|image-only/i)
    end
  end

  describe "format coverage / registry" do
    it "unknown / unsupported formats return nil so the caller falls back" do
      Dir.mktmpdir do |d|
        path = File.join(d, "thing.bin")
        File.binwrite(path, "\x00\x01\x02\x03")
        expect(described_class.to_markdown(path, mime: "application/octet-stream")).to be_nil
      end
    end

    it "advertises at least the pure-ruby formats as available" do
      expect(Rubino::Documents::Registry.available_formats)
        .to include("plain/code", "csv", "json", "xml", "html")
    end
  end

  describe "degradation — optional gem not loadable" do
    # The core safety contract: when a converter's optional gem can't be
    # required, the converter reports itself unavailable and to_markdown returns
    # nil (so the caller falls back to the shell hint) -- never raises.
    it "returns nil for a format whose converter is unavailable, without raising" do
      Dir.mktmpdir do |d|
        path = File.join(d, "sheet.xlsx")
        File.binwrite(path, "PK\x03\x04#{"\x00" * 64}")

        allow_any_instance_of(Rubino::Documents::Converters::Xlsx) # rubocop:disable RSpec/AnyInstance
          .to receive(:available?).and_return(false)

        xlsx_mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        result = nil
        expect { result = described_class.to_markdown(path, mime: xlsx_mime) }
          .not_to raise_error
        expect(result).to be_nil
      end
    end

    it "never raises out of to_markdown even on a converter exception" do
      Dir.mktmpdir do |d|
        path = File.join(d, "x.csv")
        File.write(path, "a,b\n1,2\n")
        allow_any_instance_of(Rubino::Documents::Converters::Csv) # rubocop:disable RSpec/AnyInstance
          .to receive(:convert).and_raise(RuntimeError, "boom")
        expect { described_class.to_markdown(path, mime: "text/csv") }.not_to raise_error
        expect(described_class.to_markdown(path, mime: "text/csv")).to be_nil
      end
    end
  end
end
